version: "3.8"

services:
  app:
    build: .
    image: veselica:latest
    environment:
      DB_HOST: db
      DB_USER: uporabnik
      DB_PASS: geslo
      DB_NAME: veselica
    #ports:
    #  - 8000:80
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - proxy_network

  db:
    image: mariadb:12
    environment:
      MARIADB_ROOT_PASSWORD: geslo
      MARIADB_DATABASE: veselica
      MARIADB_USER: uporabnik
      MARIADB_PASSWORD: geslo
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - proxy_network

  proxy:
    image: nginx:latest
    restart: unless-stopped
    environment:
      APP_DOMAIN: devops-sk-01.lrk.si
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - proxy_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  db_data:

networks:
  proxy_network:

